# matrix multiplication

In [21]:
import numpy as np

# Define a 2x2 matrix using NumPy array
matrix_A = np.array([[2,2,1],
                     [0,4,-2]])
matrix_B = np.array([[7,6],
                   [-1,1],
                    [-7,6]])

matrix_C = np.dot(matrix_A, matrix_B)
matrix_C

array([[ 5, 20],
       [10, -8]])

In [55]:

# Accessing elements of the matrix
print(matrix[0, 0])  # prints the element in the first row, first column (1)
print(matrix[1, 1])  # prints the element in the second row, second column (4)

NameError: name 'matrix' is not defined

# identity matrix

In [20]:
import numpy as np

# Define a 2x3 matrix using NumPy array
matrix_A = np.array([[1,2,3],
                   [-1, 3,4],
                    ])
# multiply by a 3x3 identity matrxi
matrix_I = np.array([[1,0,0],
                   [0,1,0],
                    [0,0,1]])
# what if it's a 3x4 id matrixt?
matrix_I3x4 = np.array([[1,0,0,0],
                   [0,1,0,0],
                    [0,0,1,0]])

matrix_AI = np.dot(matrix_A, matrix_I)
matrix_AI3x4 = np.dot(matrix_A, matrix_I3x4)
print(matrix_AI)
print(matrix_AI3x4)

[[ 1  2  3]
 [-1  3  4]]
[[ 1  2  3  0]
 [-1  3  4  0]]


# Here are some examples 

In [23]:
matrix_A = np.array([[5,3,1],
                   [-2,2,4],
                    [7,0,1]])
matrix_B = np.array([[2],
                     [9],
                    [-3]])

matrix_C = np.dot(matrix_A, matrix_B)
matrix_C

array([[34],
       [ 2],
       [11]])

In [25]:
np.shape(matrix_A)
np.shape(matrix_B)

(3, 1)

# Week 3

## Linear combinations

In [6]:
import numpy as np

# Define the vectors as NumPy arrays
vector_a1 = np.array([[1],
                   [-2],
                   [-5]])
vector_a2 = np.array([[2],
                   [5],
                   [6]])

# Define the coefficients for the linear combination
coefficients = [2, 3]  # Coefficients for vector1 and vector2, respectively

# Perform the linear combination
result = coefficients[0] * vector_a1 + coefficients[1] * vector_a2

print("Linear combination result:", result)

Linear combination result: [[ 8]
 [11]
 [ 8]]


### is there such a linear combination such that the outcom is vector b

In [32]:
vector_b = np.array([[7],
                   [4],
                   [-3]])


matrix1 = np.column_stack((vector_a1, vector_a2))
matrix1

array([[ 1,  2],
       [-2,  5],
       [-5,  6]])

In [31]:
vector_b

array([[ 7],
       [ 4],
       [-3]])

### Gaussian elimination

In [27]:


import numpy as np

def gaussian_elimination(A, b):
    """
    Perform Gaussian elimination to solve the system of linear equations Ax = b.
    A: coefficient matrix (n x n)
    b: constant vector (n x 1)
    Returns the solution vector x.
    """
    n = len(A)

    A = A.astype(np.float64)
    b = b.astype(np.float64)
    
    # Forward elimination
    for pivot_row in range(n):
        # Partial pivoting: find the row with the largest absolute value in the pivot column
        max_row = pivot_row
        for i in range(pivot_row + 1, n):
            if abs(A[i, pivot_row]) > abs(A[max_row, pivot_row]):
                max_row = i
        # Swap rows to make the pivot element the largest in its column
        A[[pivot_row, max_row]] = A[[max_row, pivot_row]]
        b[[pivot_row, max_row]] = b[[max_row, pivot_row]]
        
        # Eliminate all entries below the pivot
        for i in range(pivot_row + 1, n):
            factor = A[i, pivot_row] / A[pivot_row, pivot_row]
            A[i, pivot_row:] -= factor * A[pivot_row, pivot_row:]
            b[i] -= factor * b[pivot_row]
    
    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]
    
    return x





In [28]:
# Example usage
A = np.array([[ 3,4,4],
           [6,8,4],
             [0,2,2]]) # Specify dtype=float64
b = np.array([[3],[6], [4]])    # Specify dtype=float64

solution = gaussian_elimination(A,b)
#solution = gaussian_elimination(A,b)
print("Solution:", solution)

Solution: [-1.66666667  2.          0.        ]


/tmp/ipykernel_14097/1755774307.py:35: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]


In [38]:
np.shape(b)

(3, 1)

In [49]:
>>> import sympy 
>>> import numpy as np

>>> _, inds2 = sympy.Matrix(A).T.rref()   # to check the rows you need to transpose!
inds2
[0, 1, 3]

[0, 1, 3]

# finding matrix inverse 

In [34]:
matrix = np.array([[1,8,4], [0,2,2], [3,6,2]])
matrix_inverse = np.linalg.inv(matrix)
matrix_inverse

array([[-0.5  ,  0.5  ,  0.5  ],
       [ 0.375, -0.625, -0.125],
       [-0.375,  1.125,  0.125]])

# Week 4

### determinant

In [24]:
matrix = np.array([[7,3],
                  [0,4]])

In [25]:
determinant = np.linalg.det(matrix)
determinant

27.999999999999996

In [26]:

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[7. 4.]

Eigenvectors:
[[ 1.         -0.70710678]
 [ 0.          0.70710678]]


In [83]:
# finding an eigenvector
matrix_example = np.array([[1,6],
                     [5,2]])
matrix_id = np.array([[1,0],
                     [0,1]])


In [85]:
matrix_example - 7*matrix_id

array([[-6,  6],
       [ 5, -5]])

In [1]:
# Week 5


In [16]:
# calculate norm of vector 
vector_a = np.array([3,2,4])
vector_b = np.array([1,5,2])

a_sub_b = vector_a - vector_b
norm = np.linalg.norm(a_sub_b)
norm

4.123105625617661

In [17]:
norm*norm

17.0

# orthogonal projection 

In [18]:
import numpy as np

def orthogonal_projection(vector, onto):
    # Normalize the onto vector
    onto_normalized = onto / np.linalg.norm(onto)
    # Compute the dot product of the vector and onto vector
    dot_product = np.dot(vector, onto_normalized)
    # Project the vector onto the onto vector
    projection = dot_product * onto_normalized
    return projection

# Example vectors
vector = np.array([3, 4, 5])
onto = np.array([1, 0, 0])

# Compute the orthogonal projection
projection = orthogonal_projection(vector, onto)

print("Original vector:", vector)
print("Vector to project onto:", onto)
print("Orthogonal projection:", projection)


Original vector: [3 4 5]
Vector to project onto: [1 0 0]
Orthogonal projection: [3. 0. 0.]


# Least squares

In [36]:
import numpy as np

# Define your data
X = np.array([[.1, -.6], [.1, -.2], [.1, .1], [.1, .7]])
y = np.array([-.1, .2,.1,.6])

# Solve the least squares problem
coefficients, residuals, rank, singular_values = np.linalg.lstsq(X, y, rcond=None)

# Print the solution
print("Coefficients:", coefficients)
print("Residuals:", residuals)
print("Rank of the coefficient matrix:", rank)
print("Singular values of the coefficient matrix:", singular_values)


Coefficients: [2.  0.5]
Residuals: [0.035]
Rank of the coefficient matrix: 2
Singular values of the coefficient matrix: [0.9486833 0.2      ]




# random stuff

In [32]:
a = np.array([[0],[5],[4]]).T
b = np.array([[15],[-4],[-5]])
np.dot(a,b)

array([[-40]])

In [31]:
b

array([[15, -4, -5]])